### ISSUE TITLE
`scPCA` with `cv = n` randomly throws errors

### ISSUE THREAD

**Issue by PhilBoileau** [PhilBoileau/scPCA#28]
The `scPCA` function sometimes throws an error when using cross-validation to tune hyperparements. This only occurs with certain datasets. Here is a reproducible example:

```
library(scPCA)
library(SingleCellExperiment)
library(splatter)
library(scater)

# simulate some scRNA-seq data, save as sce object
params <- newSplatParams(
  seed = 6757293,
  nGenes = 500,
  batchCells = c(150, 150),
  batch.facLoc = c(0.05, 0.05),
  batch.facScale = c(0.05, 0.05),
  group.prob = rep(1/3, 3),
  de.prob = c(0.1, 0.05, 0.1),
  de.downProb = c(0.1, 0.05, 0.1),
  de.facLoc = rep(0.2, 3),
  de.facScale = rep(0.2, 3)
)

sim_groups_sce <- splatSimulate(params, method = "groups")

# get the logcounts of the data
sim_groups_sce <- normalize(sim_groups_sce)

# remove all cells without variation in counts
sim_groups_sce <- sim_groups_sce[which(rowVars(counts(sim_groups_sce)) != 0), ]

# extract the logcoount matrices of the target and background datasets
tg <- t(logcounts(sim_groups_sce)[, which(sim_groups_sce$Group != "Group2")])
bg <- t(logcounts(sim_groups_sce)[, which(sim_groups_sce$Group == "Group2")])

# run cross-validated cPCA
scPCA(target = tg, background = bg, scale = TRUE,
      penalties = 0, n_centers = 2, cv = 5)
```
```
Error: All columns in a tibble must be 1d or 2d objects:
* Column `ave_sil_widths` is NULL
```
`rlang::last_trace()` output: 
```
<error/rlang_error>
All columns in a tibble must be 1d or 2d objects:
* Column `ave_sil_widths` is NULL
Backtrace:
     █
  1. └─scPCA::scPCA(...)
  2.   ├─`%>%`(...)
  3.   │ └─base::eval(lhs, parent, parent)
  4.   │   └─base::eval(lhs, parent, parent)
  5.   └─base::lapply(...)
  6.     └─scPCA:::FUN(X[[i]], ...)
  7.       ├─tibble::as_tibble(...)
  8.       └─tibble:::as_tibble.list(...)
  9.         └─tibble:::lst_to_tibble(x, .rows, .name_repair, col_lengths(x))
 10.           └─tibble:::check_valid_cols(x)
```

This bug seems to be insensitive to the number of folds specified by `cv`, and to the number of clusters specified by `n_centers`.

**Comment by nhejazi** [comment]
This turns out to be an interesting bug, only slightly related to cross-validation. The issue arises from the formulation of `fitGrid` and could in theory happen with any dataset regardless of whether cross-validation is used. Specifically, consider the dataset above, which (due to the data-generating process) has columns with many of the same values, possibly because it comes from a counting process of some such. For a given run of `fitGrid`, we have (at https://github.com/PhilBoileau/scPCA/blob/master/R/fitGrid.R#L98-L103)
```r
Browse[1]> sum(colSums(is.na(target)))
[1] 0
```
This naturally leads to the desired result where the computed values in the list `subspaces` are as desired. However, when using `target_valid` from a given CV fold, we instead have
```r
Browse[1]> sum(colSums(is.na(target_valid)))
[1] 117
```
where the `NA` values are generated by the call to `scale` (when the eponymous argument is set `scale = TRUE`). This happens because, for this smaller split of the data, there happen to be some columns in which all values are exactly the same, resulting in a variance of zero. When `scale` then divides by the standard deviation, these values are replaced by `NA`/`NaN`. This is then propagated to the procedure that creates `subspaces` so that we have, e.g.,
```r
[[40]]
         V1  V2
Cell7   NaN NaN
Cell12  NaN NaN
Cell17  NaN NaN
Cell19  NaN NaN
Cell31  NaN NaN
Cell35  NaN NaN
Cell45  NaN NaN
Cell52  NaN NaN
Cell57  NaN NaN
Cell66  NaN NaN
Cell72  NaN NaN
Cell76  NaN NaN
Cell78  NaN NaN
Cell79  NaN NaN
```
After the remainder of the code in `fitGrid` is called, the result is that the intended output is empty. Thus, this only happens _sometimes_ with cross-validation --- but more often that it would for non-sample-split data --- since after sample-splitting, some columns may have all the same value more often by chance. In principle, it could also happen for non-sample-split data.

_Note:_ since these appear to be log-transformed, normalized counts, probably the only reason all values in a column would be the same would be if they were all zero. Probably `scale` should be replaced by an internal function `safeColScale` that circumvents the issue of inducing `NA` by instead setting those values to zero. Will do this in an incoming PR.
